version: '3.2'

services:
  db:
    image: mongo
    restart: always
    environment:
      #MONGO_INITDB_DATABASE: pvtdb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      #MONGO_NON_ROOT_USERNAME: pvt
      #MONGO_NON_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "5000:5000"
    expose:
     - 5000
    depends_on:
      - db
    volumes:
      - ./src:/src/
